[project]
name = "EmbeddingCompare"
version = "0.1.0"
description = "Comparative evaluation of embedding models for narrative segmentation"
requires-python = ">=3.8"
dependencies = [
    "sentence-transformers>=2.2.0",
    "torch>=1.12.0",
    "numpy>=1.21.0",
    "scikit-learn>=1.0.0",
]
